name: Feature Request
description: Suggest a new tool, platform, or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New tool to mirror
        - New platform support
        - Workflow improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your feature request in detail
      placeholder: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any links, references, or context that would help
      placeholder: Links to upstream repos, platform details, etc.
    validations:
      required: false
