name: Tool Update Request
description: Request an update to a specific tool version
title: "[Update]: "
labels: ["update"]
body:
  - type: markdown
    attributes:
      value: |
        Request that a specific tool be updated to a newer version.

  - type: dropdown
    id: tool
    attributes:
      label: Tool
      description: Which tool needs updating?
      options:
        - FFmpeg
        - yt-dlp
        - mp4decrypt
        - MP4Box
        - N_m3u8DL-RE
        - aria2c
        - fpcalc
        - get_iplayer
        - Votify
        - gytmdl
        - gamdl
        - AMdecrypt
        - Wrapper
    validations:
      required: true

  - type: input
    id: current_version
    attributes:
      label: Current Mirrored Version
      description: What version is currently in the latest release? (if known)
      placeholder: e.g., v2024.10.22
    validations:
      required: false

  - type: input
    id: desired_version
    attributes:
      label: Desired Version
      description: What version should it be updated to?
      placeholder: e.g., v2025.01.15 or "latest"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Update
      description: Why is this update needed?
      placeholder: Bug fix, new feature, security patch, etc.
    validations:
      required: false
